app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
 Route::get('reg', ['uses' => 'UsersController@regis', 'as' => 'reg']);
  Route::get('replicate', ['uses' => 'CarController@testreplicate', 'as' => 'testreplicate']);
//Route::get('/', function () { return view('auth/login');  });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => ['web']], function () {
	//Route::group(['middleware' => 'web'], function () {
   // Route::auth();
     Route::get('login', function () {
       return view('auth/login');
    });
     Route::group(['prefix' => 'api'], function () {
		Route::any('users/login', ['uses' => 'UsersController@login', 'as' => 'api.users.login']);
		Route::any('users/datatable', ['uses' => 'UsersController@datatable', 'as' => 'api.users.datatable' ]);
		Route::any('users/printcounts7days/{id}', ['uses' => 'UsersController@printcounts7days', 'as' => 'api.users.printcounts7days' ]);
		Route::any('cars/chasisno', ['uses' => 'CarController@chasisno', 'as' => 'api.cars.chasisno' ]);
		Route::any('cars/singlecar', ['uses' => 'CarController@singlecar', 'as' => 'api.cars.singlecar' ]);
		Route::any('cars/searchchasisno', ['uses' => 'CarController@searchchasisno', 'as' => 'api.cars.searchchasisno' ]);
		Route::any('cars/carmakesearch', ['uses' => 'CarController@carmakesearch', 'as' => 'api.cars.carmakesearch' ]);
		Route::any('cars/carcolours', ['uses' => 'CarController@carcolours', 'as' => 'api.cars.carcolours' ]);
		Route::any('cars/clearingagents', ['uses' => 'CarController@clearingagents', 'as' => 'api.cars.clearingagents' ]);
		Route::any('cars/importersnames', ['uses' => 'CarController@importersnames', 'as' => 'api.cars.importersnames' ]);
		Route::any('cars/importersaddress', ['uses' => 'CarController@importersaddress', 'as' => 'api.cars.importersaddress' ]);
		Route::any('cars/datatable/{fromdate?}/{todate?}', ['uses' => 'CarController@datatable', 'as' => 'api.cars.datatable' ]);
		Route::any('cars/reprintsdatatable/{fromdate?}/{todate?}', ['uses' => 'CarController@reprintsdatatable', 'as' => 'api.cars.reprintsdatatable' ]);
		Route::any('cars/singlereprintdatatable/{id}', ['uses' => 'CarController@singlereprintdatatable', 'as' => 'api.cars.singlereprintdatatable' ]);
		Route::any('cars/singlereprintdatatable/{id}/{userid}', ['uses' => 'CarController@singlereprintwithdatesdatatable', 'as' => 'api.cars.singlereprintwithdatesdatatable' ]);
		Route::any('cars/editsdatatable/{fromdate?}/{todate?}', ['uses' => 'CarController@editsdatatable', 'as' => 'api.cars.editsdatatable' ]);
		Route::any('cars/singleditdatatable/{id}', ['uses' => 'CarController@singleditdatatable', 'as' => 'api.cars.singleditdatatable' ]);
		Route::any('cars/singlereeditwithdatesdatatable/{id}/{userid}', ['uses' => 'CarController@singlereeditwithdatesdatatable', 'as' => 'api.cars.singlereeditwithdatesdatatable' ]);
		
		Route::any('ships/singleship', ['uses' => 'ShipController@singleship', 'as' => 'api.ships.singleship' ]);
		Route::post('cars/inspecatedcarsave', ['uses' => 'CarController@inspecatedcarsave', 'as' => 'api.cars.inspecatedcarsave' ]);
		Route::any('cars/fullcarsave', ['uses' => 'CarController@fullcarsave', 'as' => 'api.cars.fullcarsave' ]);
		Route::any('cars/chartdata', ['uses' => 'CarController@chartdata', 'as' => 'api.cars.chartdata' ]);
		Route::any('cars/updateprint', ['uses' => 'CarController@updateprint', 'as' => 'api.cars.updateprint' ]);
		Route::any('cars/quartilespiechart', ['uses' => 'CarController@quartilespiechartdata', 'as' => 'api.cars.quartilespiechart' ]);
		Route::any('cars/daterangequartilespiechart', ['uses' => 'CarController@daterangequartilespiechart', 'as' => 'api.cars.daterangequartilespiechart' ]);
		Route::any('environmental/updateprint', ['uses' => 'EnvironmentalController@updateprint', 'as' => 'api.environmental.updateprint' ]);
		Route::any('environmental/datatable', ['uses' => 'EnvironmentalController@datatable', 'as' => 'api.environmental.datatable' ]);
		Route::any('environmental/chartdata', ['uses' => 'EnvironmentalController@chartdata', 'as' => 'api.environmental.chartdata' ]);
		Route::any('invoice/datatable', ['uses' => 'InvoiceController@datatable', 'as' => 'api.invoice.datatable' ]);
		
		//roles 
		 Route::get('users/setroles', ['uses' => 'UsersController@setroles', 'as' => 'api.users.setroles']);
		 Route::get('users/usersetrole', ['uses' => 'UsersController@usersetrole', 'as' => 'usersetrole']);
		 Route::get('users/usersetpermission', ['uses' => 'UsersController@usersetpermission', 'as' => 'usersetpermission']);
		 Route::get('users/useraddpermission', ['uses' => 'UsersController@useraddpermission', 'as' => 'useraddpermission']);
		 Route::get('users/userremovepermission', ['uses' => 'UsersController@userremovepermission', 'as' => 'userremovepermission']);
		 Route::get('users/roleaddpermission', ['uses' => 'UsersController@roleaddpermission', 'as' => 'api.users.roleaddpermission']);
		 
		Route::resource('users', 'UsersController');
		Route::resource('ships', 'ShipController');
		Route::resource('cars', 'CarController');
		Route::resource('environmental', 'EnvironmentalController');
		Route::resource('invoice', 'InvoiceController');
		
	});

   // Route::get('/', function () { return view('admin.dashboard');  });
   // Route::get('/home', 'HomeController@index');
   Route::get('/', ['uses' => 'UsersController@checklogin', 'as' => 'api.users.checklogin']);
    Route::group(['as' => 'admin.','prefix' => 'admin'], function () {
            
            
             Route::get('dashboard/logout', ['as' => 'logout', 'uses' => 'UsersController@logout']);
             
              Route::group(['as' => 'dashboard.','prefix' => 'dashboard'], function () {
				  Route::get('/',['uses' => 'DashboardController@dashboard', 'as' => 'index'] );
                  Route::any('datatable', ['uses' => 'DashboardController@datatable', 'as' => 'datatable' ]);
                  Route::any('chartdata', ['uses' => 'DashboardController@chartdata', 'as' => 'chartdata' ]);
                  Route::any('randomgenerator', ['uses' => 'DashboardController@randomgenerator', 'as' => 'randomgenerator' ]);
                  Route::any('getdailynotification', ['uses' => 'DashboardController@getdailynotification', 'as' => 'getdailynotification' ]);
		         
               
             
            });
             Route::get('newship', ['uses' => 'DashboardController@newship', 'as' => 'newship']);
            
            
             Route::group(['as' => 'car.','prefix' => 'car'], function () {
				 
               Route::get('carinspection', ['uses' => 'DashboardController@carinspection', 'as' => 'carinspection']);
               Route::get('inspectedcar', ['uses' => 'DashboardController@inspectedcar', 'as' => 'inspectedcar']);
               Route::get('fullcarrecord', ['uses' => 'DashboardController@fullcarrecord', 'as' => 'fullcarrecord']);
               Route::get('allcarrecords/{fromdate?}/{todate?}', ['uses' => 'DashboardController@allcarrecords', 'as' => 'allcarrecords']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@carreprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@caredit', 'as' => 'edit']);
             
            });
             Route::group(['as' => 'environmental.','prefix' => 'environmental'], function () {
				 
               Route::get('newrecord', ['uses' => 'DashboardController@newenvironmentalrecord', 'as' => 'newenvironmentalrecord']);
               Route::get('allrecords', ['uses' => 'DashboardController@allenvironmentalrecords', 'as' => 'allenvironmentalrecords']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@environmentalreprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@environmentaledit', 'as' => 'edit']);
               
             
            });
            Route::group(['as' => 'invoice.','prefix' => 'invoice'], function () {
				 
               Route::get('newinvoice', ['uses' => 'DashboardController@newinvoice', 'as' => 'newinvoice']);
               Route::get('allinvoice', ['uses' => 'DashboardController@allinvoice', 'as' => 'allinvoice']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@invoicereprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@invoiceedit', 'as' => 'edit']);
               
             
            });
             Route::group(['as' => 'users.','prefix' => 'users'], function () {
				  Route::get('newuser', ['uses' => 'DashboardController@register', 'as' => 'register']);
				  Route::get('listuser', ['uses' => 'DashboardController@listuser', 'as' => 'listuser']);
				  Route::get('user/{id}', ['uses' => 'DashboardController@singleuser', 'as' => 'user' ]);
				  Route::get('roles', ['uses' => 'DashboardController@usersroles', 'as' => 'usersroles' ]);
				   Route::get('role/{id}', ['uses' => 'DashboardController@singlerole', 'as' => 'singlerole' ]);
				   Route::get('newsinglerole', ['uses' => 'DashboardController@newsinglerole', 'as' => 'newsinglerole' ]);
				 
             });
             Route::group(['as' => 'analysis.','prefix' => 'analysis'], function () {

resources/views/admin/dashboard.blade.php
<?php 
use Carbon\Carbon ;
$now = Carbon::now() ;

$Dfromdate = $now->startOfMonth()->toFormattedDateString() ;
$Dtodate = $now->endOfMonth()->toFormattedDateString() ;
?>
@extends('layouts.app')



@section('title',  $title ) 

@section('content')

@if($user->hasAccess(['admin.dashboard.index']))

 <div class="row">
           
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-aqua"><i class="ion ion-android-car"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Car Records</span>
                  <span class="info-box-number">{{ $carCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-red"><i class="ion ion-android-boat"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Env Records</span>
                  <span class="info-box-number">{{ $envCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix visible-sm-block"></div>

            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Invoices</span>
                  <span class="info-box-number">{{ $invCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Users</span>
                  <span class="info-box-number">{{ $userCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          
  
</div><!-- /.row -->





<div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Monthly Recap Report</h3>
                  <div class="box-tools pull-right">
                   
                     <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-12">
                      <p class="text-center">
                        <strong>Car Records: {{ $Dfromdate or '' }} - {{ $Dtodate or '' }}</strong>
                      </p>
                      <div class="chart">
                        <!-- Carrecords Chart Canvas -->
                        <canvas id="carrecordsLineChart" style="height: 180px;"></canvas>
                      </div><!-- /.chart-responsive -->
                    </div><!-- /.col -->
                   </div><!-- /.row -->
                </div><!-- ./box-body -->
                 </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

@endif
<div class="row">
            <div class="col-md-12">
				<!-- TABLE: LATEST ORDERS -->
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Latest Car Records</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
					<div class="row">
            <div class="col-md-12">
                 <table id="car_environmental_records" class="table table-bordered table-striped">
                    <thead>
                       <tr>
                        <th></th>
                        <th>Chassisno No</th>
                        <th>Importer Name</th>
                        <th>Customs No</th>
                        <th>Car Make</th>
                        <th>System user</th>
                        <th>Created On</th>
                         <th></th>
                      </tr>
                    </thead>
                     <tbody>
				     </tbody>
                    
                  </table>
                  </div>
                </div>
                </div><!-- /.box-body -->
                
              </div><!-- /.box -->
           
            </div><!-- /.col -->
</div><!-- /.row -->
@endsection


@push('scripts')



<script src=" {{ asset ('js/jquery.dataTables.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.buttons.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.colVis.min.js') }}"></script>
<script src=" {{ asset ('js/jszip.min.js') }}"></script>
<script src=" {{ asset ('js/pdfmake.min.js') }}"></script>
<script src=" {{ asset ('js/vfs_fonts.js') }}"></script>
<script src=" {{ asset ('js/buttons.html5.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.print.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.bootstrap.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.responsive.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset ('plugins/chartjs/Chart.min.js') }}"></script>
<script src="{{ asset ('js/dashchartcarrecords.js') }}"></script>


<script type="text/javascript">
      $(function () {
       
       var t =    $('#car_environmental_records').DataTable({
				processing: true,
				responsive: true,
				 "columnDefs": [ {
					"searchable": false,
					"orderable": false,
					"targets": 0
				} ],
				//~ "autoWidth": false,
				 //~ "columnDefs": [
					//~ { "width": "5%", "targets": 0 },
					//~ { "width": "20%", "targets": 1 },
					//~ { "width": "15%", "targets": 2 },
					//~ { "width": "15%", "targets": 3 },
					//~ { "width": "15%", "targets": 4 },
					//~ { "width": "5%", "targets": 5 },
					//~ { "width": "15%", "targets": 6 },
					//~ { "width": "10%", "targets": 7 }
				  //~ ],
				serverSide: true,
				dom: 'Bfrtip',
				 buttons: [
					
					{
						extend: 'excelHtml5',
						exportOptions: {
							columns: [  0,1, 2,3,4, 5 , 6 ]
						}
					},
					{
						extend: 'pdfHtml5',
						exportOptions: {
							columns: [ 0, 1, 2,3,4, 5, 6 ]
						}
					},
					{
						extend: 'print',
						exportOptions: {
							columns: [ 0, 1, 2,3,4, 5, 6]
						}
					}
					
					
				],
				//~ buttons: [
					//~ 'print' , 'excel', 'pdf'
				//~ ],
				//~ "fnCreatedRow": function (row, data, index) {
					//~ $('td', row).eq(0).html(index + 1);
				//~ },
				 "order": [[ 1, 'asc' ]],
				"pageLength": 10,
			    ajax: '{!! route('admin.dashboard.datatable') !!}',
			    
				columns: [
					 {data: 'rownum', name: 'rownum' ,orderable: false, searchable: false},
					{ data: 'chassisno', name: 'cars.chassisno' },
					{ data: 'importername', name: 'importers.name' },
					{ data: 'customsno', name: 'cars.customsno' },
					{ data: 'name', name: 'cars.name' },
					{ data: 'first_name', name: 'users.first_name' },
					{ data: 'created_at', name: 'cars.created_at' },
					{ data: 'action', name: 'cars.id' ,orderable: false, searchable: false},
					
				]
			});
			
			 t.on( 'order.dt search.dt', function () {
				t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
					cell.innerHTML = i+1;
				} );
			} ).draw();
			
      });
   
    
    </script>
    
    <script type="text/javascript">
     LaravelApiroute["dashcarrecordschart"] = " {!! route('admin.dashboard.chartdata') !!}";
     
    </script>
    
@endpush

@push('css')
 
 <link rel="stylesheet" href="{{ asset ('css/dataTables.bootstrap.min.css') }}">
 
 <link rel="stylesheet" href="{{ asset ('css/buttons.bootstrap.min.css') }}">
@endpush

resources/views/admin/dashboardtest.blade.php
<?php 
use Carbon\Carbon ;
$now = Carbon::now() ;

$Dfromdate = $now->startOfMonth()->toFormattedDateString() ;
$Dtodate = $now->endOfMonth()->toFormattedDateString() ;
?>
@extends('layouts.app')



@section('title',  $title ) 

@section('content')

 <div class="row">
           
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-aqua"><i class="ion ion-android-car"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Car Records</span>
                  <span class="info-box-number">{{ $carCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-red"><i class="ion ion-android-boat"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Env Records</span>
                  <span class="info-box-number">{{ $envCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix visible-sm-block"></div>

            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Invoices</span>
                  <span class="info-box-number">{{ $invCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Users</span>
                  <span class="info-box-number">{{ $userCount }}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          
  
</div><!-- /.row -->

<div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Monthly Recap Report</h3>
                  <div class="box-tools pull-right">
                   
                     <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-12">
                      <p class="text-center">
                        <strong>Car Records: {{ $Dfromdate or '' }} - {{ $Dtodate or '' }}</strong>
                      </p>
                      <div class="chart">
                        <!-- Carrecords Chart Canvas -->
                        <canvas id="carrecordsLineChart" style="height: 180px;"></canvas>
                      </div><!-- /.chart-responsive -->
                    </div><!-- /.col -->
                   </div><!-- /.row -->
                </div><!-- ./box-body -->
                 </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->


<div class="row">
            <div class="col-md-12">
				<!-- TABLE: LATEST ORDERS -->
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Latest Car Records</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
					<div class="row">
            <div class="col-md-12">
                 <table id="car_environmental_records" class="table table-bordered table-striped">
                    <thead>
                       <tr>
                        <th></th>
                        <th>Chassisno No</th>
                        <th>Importer Name</th>
                        <th>Customs No</th>
                        <th>Car Make</th>
                        <th>System user</th>
                        <th>Created On</th>
                         <th></th>
                      </tr>
                    </thead>
                     <tbody>
				     </tbody>
                    
                  </table>
                  </div>
                </div>
                </div><!-- /.box-body -->
                
              </div><!-- /.box -->
           
            </div><!-- /.col -->
</div><!-- /.row -->
@endsection


@push('scripts')

<script src=" {{ asset ('js/jquery.dataTables.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.buttons.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.colVis.min.js') }}"></script>
<script src=" {{ asset ('js/jszip.min.js') }}"></script>
<script src=" {{ asset ('js/pdfmake.min.js') }}"></script>
<script src=" {{ asset ('js/vfs_fonts.js') }}"></script>
<script src=" {{ asset ('js/buttons.html5.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.print.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.bootstrap.min.js') }}"></script>
<script src=" {{ asset ('js/dataTables.responsive.min.js') }}"></script>
<script src=" {{ asset ('js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset ('plugins/chartjs/Chart.min.js') }}"></script>
<script src="{{ asset ('js/dashchartcarrecords.js') }}"></script>

<script type="text/javascript">
      $(function () {
       
       var t =    $('#car_environmental_records').DataTable({
				processing: true,
				responsive: true,
				 "columnDefs": [ {
					"searchable": false,
					"orderable": false,
					"targets": 0
				} ],
				//~ "autoWidth": false,
				 //~ "columnDefs": [
					//~ { "width": "5%", "targets": 0 },
					//~ { "width": "20%", "targets": 1 },
					//~ { "width": "15%", "targets": 2 },
					//~ { "width": "15%", "targets": 3 },
					//~ { "width": "15%", "targets": 4 },
					//~ { "width": "5%", "targets": 5 },
					//~ { "width": "15%", "targets": 6 },
					//~ { "width": "10%", "targets": 7 }
				  //~ ],
				serverSide: true,
				dom: 'Bfrtip',
				 buttons: [
					
					{
						extend: 'excelHtml5',
						exportOptions: {
							columns: [  0,1, 2,3,4, 5 , 6 ]
						}
					},
					{
						extend: 'pdfHtml5',
						exportOptions: {
							columns: [ 0, 1, 2,3,4, 5, 6 ]
						}
					},
					{
						extend: 'print',
						exportOptions: {
							columns: [ 0, 1, 2,3,4, 5, 6]
						}
					}
					
					
				],
				//~ buttons: [
					//~ 'print' , 'excel', 'pdf'
				//~ ],
				//~ "fnCreatedRow": function (row, data, index) {
					//~ $('td', row).eq(0).html(index + 1);
				//~ },
				 "order": [[ 1, 'asc' ]],
				"pageLength": 10,
			    ajax: '{!! route('admin.dashboard.datatable') !!}',
			    
				columns: [
					 {data: 'rownum', name: 'rownum' ,orderable: false, searchable: false},
					{ data: 'chassisno', name: 'cars.chassisno' },
					{ data: 'importername', name: 'importers.name' },
					{ data: 'customsno', name: 'cars.customsno' },
					{ data: 'name', name: 'cars.name' },
					{ data: 'first_name', name: 'users.first_name' },
					{ data: 'created_at', name: 'cars.created_at' },
					{ data: 'action', name: 'cars.id' ,orderable: false, searchable: false},
					
				]
			});
			
			 t.on( 'order.dt search.dt', function () {
				t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
					cell.innerHTML = i+1;
				} );
			} ).draw();
			
      });
   
    
    </script>
    
    <script type="text/javascript">
    LaravelApiroute["dashcarrecordschart"] = " {!! route('admin.dashboard.chartdata') !!}";
    
    </script>
    
@endpush

@push('css')
 
 <link rel="stylesheet" href="{{ asset ('css/dataTables.bootstrap.min.css') }}">
 
 <link rel="stylesheet" href="{{ asset ('css/buttons.bootstrap.min.css') }}">
@endpush