app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
 Route::get('reg', ['uses' => 'UsersController@regis', 'as' => 'reg']);
  Route::get('replicate', ['uses' => 'CarController@testreplicate', 'as' => 'testreplicate']);
//Route::get('/', function () { return view('auth/login');  });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => ['web']], function () {
	//Route::group(['middleware' => 'web'], function () {
   // Route::auth();
     Route::get('login', function () {
       return view('auth/login');
    });
     Route::group(['prefix' => 'api'], function () {
		Route::any('users/login', ['uses' => 'UsersController@login', 'as' => 'api.users.login']);
		Route::any('users/datatable', ['uses' => 'UsersController@datatable', 'as' => 'api.users.datatable' ]);
		Route::any('users/printcounts7days/{id}', ['uses' => 'UsersController@printcounts7days', 'as' => 'api.users.printcounts7days' ]);
		Route::any('cars/chasisno', ['uses' => 'CarController@chasisno', 'as' => 'api.cars.chasisno' ]);
		Route::any('cars/singlecar', ['uses' => 'CarController@singlecar', 'as' => 'api.cars.singlecar' ]);
		Route::any('cars/searchchasisno', ['uses' => 'CarController@searchchasisno', 'as' => 'api.cars.searchchasisno' ]);
		Route::any('cars/carmakesearch', ['uses' => 'CarController@carmakesearch', 'as' => 'api.cars.carmakesearch' ]);
		Route::any('cars/carcolours', ['uses' => 'CarController@carcolours', 'as' => 'api.cars.carcolours' ]);
		Route::any('cars/clearingagents', ['uses' => 'CarController@clearingagents', 'as' => 'api.cars.clearingagents' ]);
		Route::any('cars/importersnames', ['uses' => 'CarController@importersnames', 'as' => 'api.cars.importersnames' ]);
		Route::any('cars/importersaddress', ['uses' => 'CarController@importersaddress', 'as' => 'api.cars.importersaddress' ]);
		Route::any('cars/datatable/{fromdate?}/{todate?}', ['uses' => 'CarController@datatable', 'as' => 'api.cars.datatable' ]);
		Route::any('cars/reprintsdatatable/{fromdate?}/{todate?}', ['uses' => 'CarController@reprintsdatatable', 'as' => 'api.cars.reprintsdatatable' ]);
		Route::any('cars/singlereprintdatatable/{id}', ['uses' => 'CarController@singlereprintdatatable', 'as' => 'api.cars.singlereprintdatatable' ]);
		Route::any('cars/singlereprintdatatable/{id}/{userid}', ['uses' => 'CarController@singlereprintwithdatesdatatable', 'as' => 'api.cars.singlereprintwithdatesdatatable' ]);
		Route::any('cars/editsdatatable/{fromdate?}/{todate?}', ['uses' => 'CarController@editsdatatable', 'as' => 'api.cars.editsdatatable' ]);
		Route::any('cars/singleditdatatable/{id}', ['uses' => 'CarController@singleditdatatable', 'as' => 'api.cars.singleditdatatable' ]);
		Route::any('cars/singlereeditwithdatesdatatable/{id}/{userid}', ['uses' => 'CarController@singlereeditwithdatesdatatable', 'as' => 'api.cars.singlereeditwithdatesdatatable' ]);
		
		Route::any('ships/singleship', ['uses' => 'ShipController@singleship', 'as' => 'api.ships.singleship' ]);
		Route::post('cars/inspecatedcarsave', ['uses' => 'CarController@inspecatedcarsave', 'as' => 'api.cars.inspecatedcarsave' ]);
		Route::any('cars/fullcarsave', ['uses' => 'CarController@fullcarsave', 'as' => 'api.cars.fullcarsave' ]);
		Route::any('cars/chartdata', ['uses' => 'CarController@chartdata', 'as' => 'api.cars.chartdata' ]);
		Route::any('cars/updateprint', ['uses' => 'CarController@updateprint', 'as' => 'api.cars.updateprint' ]);
		Route::any('cars/quartilespiechart', ['uses' => 'CarController@quartilespiechartdata', 'as' => 'api.cars.quartilespiechart' ]);
		Route::any('cars/daterangequartilespiechart', ['uses' => 'CarController@daterangequartilespiechart', 'as' => 'api.cars.daterangequartilespiechart' ]);
		Route::any('environmental/updateprint', ['uses' => 'EnvironmentalController@updateprint', 'as' => 'api.environmental.updateprint' ]);
		Route::any('environmental/datatable', ['uses' => 'EnvironmentalController@datatable', 'as' => 'api.environmental.datatable' ]);
		Route::any('environmental/chartdata', ['uses' => 'EnvironmentalController@chartdata', 'as' => 'api.environmental.chartdata' ]);
		Route::any('invoice/datatable', ['uses' => 'InvoiceController@datatable', 'as' => 'api.invoice.datatable' ]);
		
		//roles 
		 Route::get('users/setroles', ['uses' => 'UsersController@setroles', 'as' => 'api.users.setroles']);
		 Route::get('users/usersetrole', ['uses' => 'UsersController@usersetrole', 'as' => 'usersetrole']);
		 Route::get('users/usersetpermission', ['uses' => 'UsersController@usersetpermission', 'as' => 'usersetpermission']);
		 Route::get('users/useraddpermission', ['uses' => 'UsersController@useraddpermission', 'as' => 'useraddpermission']);
		 Route::get('users/userremovepermission', ['uses' => 'UsersController@userremovepermission', 'as' => 'userremovepermission']);
		 Route::get('users/roleaddpermission', ['uses' => 'UsersController@roleaddpermission', 'as' => 'api.users.roleaddpermission']);
		 
		Route::resource('users', 'UsersController');
		Route::resource('ships', 'ShipController');
		Route::resource('cars', 'CarController');
		Route::resource('environmental', 'EnvironmentalController');
		Route::resource('invoice', 'InvoiceController');
		
	});

   // Route::get('/', function () { return view('admin.dashboard');  });
   // Route::get('/home', 'HomeController@index');
   Route::get('/', ['uses' => 'UsersController@checklogin', 'as' => 'api.users.checklogin']);
    Route::group(['as' => 'admin.','prefix' => 'admin'], function () {
            
            
             Route::get('dashboard/logout', ['as' => 'logout', 'uses' => 'UsersController@logout']);
             
              Route::group(['as' => 'dashboard.','prefix' => 'dashboard'], function () {
				  Route::get('/',['uses' => 'DashboardController@dashboard', 'as' => 'index'] );
                  Route::any('datatable', ['uses' => 'DashboardController@datatable', 'as' => 'datatable' ]);
                  Route::any('chartdata', ['uses' => 'DashboardController@chartdata', 'as' => 'chartdata' ]);
                  Route::any('randomgenerator', ['uses' => 'DashboardController@randomgenerator', 'as' => 'randomgenerator' ]);
                  Route::any('getdailynotification', ['uses' => 'DashboardController@getdailynotification', 'as' => 'getdailynotification' ]);
		         
               
             
            });
             Route::get('newship', ['uses' => 'DashboardController@newship', 'as' => 'newship']);
            
            
             Route::group(['as' => 'car.','prefix' => 'car'], function () {
				 
               Route::get('carinspection', ['uses' => 'DashboardController@carinspection', 'as' => 'carinspection']);
               Route::get('inspectedcar', ['uses' => 'DashboardController@inspectedcar', 'as' => 'inspectedcar']);
               Route::get('fullcarrecord', ['uses' => 'DashboardController@fullcarrecord', 'as' => 'fullcarrecord']);
               Route::get('allcarrecords/{fromdate?}/{todate?}', ['uses' => 'DashboardController@allcarrecords', 'as' => 'allcarrecords']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@carreprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@caredit', 'as' => 'edit']);
             
            });
             Route::group(['as' => 'environmental.','prefix' => 'environmental'], function () {
				 
               Route::get('newrecord', ['uses' => 'DashboardController@newenvironmentalrecord', 'as' => 'newenvironmentalrecord']);
               Route::get('allrecords', ['uses' => 'DashboardController@allenvironmentalrecords', 'as' => 'allenvironmentalrecords']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@environmentalreprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@environmentaledit', 'as' => 'edit']);
               
             
            });
            Route::group(['as' => 'invoice.','prefix' => 'invoice'], function () {
				 
               Route::get('newinvoice', ['uses' => 'DashboardController@newinvoice', 'as' => 'newinvoice']);
               Route::get('allinvoice', ['uses' => 'DashboardController@allinvoice', 'as' => 'allinvoice']);
               Route::get('reprint/{id}', ['uses' => 'DashboardController@invoicereprint', 'as' => 'reprint']);
               Route::get('edit/{id}', ['uses' => 'DashboardController@invoiceedit', 'as' => 'edit']);
               
             
            });
             Route::group(['as' => 'users.','prefix' => 'users'], function () {
				  Route::get('newuser', ['uses' => 'DashboardController@register', 'as' => 'register']);
				  Route::get('listuser', ['uses' => 'DashboardController@listuser', 'as' => 'listuser']);
				  Route::get('user/{id}', ['uses' => 'DashboardController@singleuser', 'as' => 'user' ]);
				  Route::get('roles', ['uses' => 'DashboardController@usersroles', 'as' => 'usersroles' ]);
				   Route::get('role/{id}', ['uses' => 'DashboardController@singlerole', 'as' => 'singlerole' ]);
				   Route::get('newsinglerole', ['uses' => 'DashboardController@newsinglerole', 'as' => 'newsinglerole' ]);
				 
             });
             Route::group(['as' => 'analysis.','prefix' => 'analysis'], function () {

resources/views/layouts/app.blade.php
<?php 
use Carbon\Carbon ;

?>
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title> Portal Example - @yield('title')</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link href="{{ asset("css/bootstrap.css") }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/ionicons.min.css") }} " rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/all.css")}}" rel="stylesheet" type="text/css" />
   
    <link href="{{ asset("css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
    
    <link href="{{ asset("css/jquery.growl.css")}}" rel="stylesheet" type="text/css" />
    
    @stack('css')
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue  fixed sidebar-mini hold-transition 
 @unless(Sentinel::check())
   login-page
 @endunless
">

 <meta name="csrf-token" content="{{ csrf_token() }}">

@if(Sentinel::check())
   <div class="wrapper hidden-print ">

   
      @include('layouts.header')

    
      @include('layouts.sidebar')

     
      <div class="content-wrapper">
      
        <section class="content-header">
          
          
          
        </section>

       
        <section class="content">          
          
          @yield('content')
        </section>
      </div>
      
     @include('layouts.footer')
       
     
     

    </div>

 
@else
 
 @yield('login')
 
@endif
   
    
    <script src="{{ asset ("js/bootstrap.js") }}" type="text/javascript"></script>
    <script src="{{ asset ("js/jquery.growl.js") }}" type="text/javascript"></script>
    <script src="{{ asset ("plugins/slimScroll/jquery.slimscroll.min.js") }}" type="text/javascript" ></script>
    @stack('scriptsbefore')
    <script src="{{ asset ("js/app.min.js") }}" type="text/javascript"></script>
    <script src="  {{ asset ('plugins/typeahead/typeahead.bundle.min.js') }}"></script>
     <script src="  {{ asset ('js/bloodhoundLaravel.js') }}"></script>
     <script type="text/javascript"> 
	     var LaravelApiroute = {}; 
         LaravelApiroute["bloodhoundshipsearch"] = " {!! route('api.ships.singleship') !!}";
         LaravelApiroute["bloodhoundcarmakesearch"] = " {!! route('api.cars.carmakesearch') !!}";
          LaravelApiroute["bloodhoundcarcolours"] = " {!! route('api.cars.carcolours') !!}";
          LaravelApiroute["bloodhoundclearingAgents"] = " {!! route('api.cars.clearingagents') !!}"; 
          LaravelApiroute["bloodhoundimportersnames"] = " {!! route('api.cars.importersnames') !!}";
          LaravelApiroute["bloodhoundimportersaddress"] = " {!! route('api.cars.importersaddress') !!}";
          LaravelApiroute["dashurl"] =  "{!! route('admin.dashboard.index' ) !!}";
         LaravelApiroute["randomgenerator"] =  "{!! route('admin.dashboard.randomgenerator' ) !!}";
        
   </script>
   @if(Sentinel::check())
    @if($user->hasAccess(['admin.dashboard.index']))
     <script type="text/javascript"> 
        LaravelApiroute["getdailynotification"] = " {!! route('admin.dashboard.getdailynotification') !!}";
        LaravelApiroute["dailyreprintsurl"] = " {!! route('admin.reprints.all',['fromdate' => Carbon::today()->toDateString() , 'todate' => Carbon::tomorrow()->toDateString() ]) !!}";
        LaravelApiroute["dailyeditreprintsurl"] = " {!! route('admin.edits.all',['fromdate' => Carbon::today()->toDateString() , 'todate' => Carbon::tomorrow()->toDateString() ]) !!}";
        LaravelApiroute["dailyprintsurl"] = " {!! route('admin.car.allcarrecords',['fromdate' => Carbon::today()->toDateString() , 'todate' => Carbon::tomorrow()->toDateString() ]) !!}";
      </script>
	<script src=" {{ asset ('js/getdailynotification.js') }}"></script>
	@endif
	@endif
    @stack('scripts')
     <script src="{{ asset ("js/all.js") }}" type="text/javascript"></script>
     <script src="{{ asset ("js/JsBarcode.all.js") }}" type="text/javascript"></script>
     
  </body>
</html>

resources/views/layouts/footer.blade.php
<?php 
use Carbon\Carbon ;

$now = Carbon::now() ;
?>
<footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0.0
        </div>
        <strong>Copyright &copy; {{ $now->year  }} Portal Example , Developed by <a href="http://jimmycliff.me.net">Jimmy Cliff</a>.</strong> All rights reserved.
</footer>

resources/views/layouts/header.blade.php
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
 
  <a href="{!!  url('/') !!}" class="logo"><b> Portal Example </b> </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
		  @if($user->hasAccess(['admin.dashboard.index']))
		   <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu ">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label" id="show_notfication_warning_success"></span>
            </a>
            <ul class="dropdown-menu">
              
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  
                 
                </ul>
              </li>
             
            </ul>
          </li>
          @endif
		   <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="{{ asset("img/user2-160x160.jpg") }}" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">{{ $user->first_name }} {{ $user->last_name }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="{{ asset("img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
              <p>
                
                <small>{{ $user->first_name }} {{ $user->last_name }}</small>
              </p>
            </li>
            
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ route('admin.users.user' ,['id' => $user->id ])}}" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="{{ route('admin.logout') }}" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/main.blade.php
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "Admin" }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link href="{{ asset("css/bootstrap.css") }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/ionicons.min.css") }} " rel="stylesheet" type="text/css" />

    <link href="{{ asset("css/main.min.css")}}" rel="stylesheet" type="text/css" />
   
    <link href="{{ asset("css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
    @stack('css')
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
   <meta name="csrf-token" content="{{ csrf_token() }}">
    <div class="wrapper">

   
      @include('layouts.header')

    
      @include('layouts.sidebar')

     
      <div class="content-wrapper">
      
        <section class="content-header">
          <h1>
            {{ $page_title or "Page Title" }}
            <small>{{ $page_description or null }}</small>
          </h1>
          
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
          </ol>
        </section>

       
        <section class="content">          
          
          @yield('content')
        </section>
      </div>

     
     

    </div>

    
    <script src="{{ asset ("js/bootstrap.js") }}" type="text/javascript"></script>
  
    <script src="{{ asset ("js/app.min.js") }}" type="text/javascript"></script>
    
   
    
   <script type="text/javascript"> 
	    var LaravelApiroute = {}; 
    
   </script>
   
    @stack('scripts')
    
     <script src="{{ asset ("js/all.js") }}" type="text/javascript"></script>
  </body>
</html>

resources/views/layouts/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset("img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p> {{ $user->first_name }} </p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

   

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
		
     <li>
              <a href="{!! route('admin.dashboard.index') !!}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
              </a>
              
     </li>
     @if($user->hasAccess(['admin.newship']))
     <li>
		 
              <a href="{!! route('admin.newship') !!}">
                <i class="fa fa-ship"></i> <span>New Ship Record</span> 
              </a>
    </li>
    @endif
    @if($user->hasAccess(['admin.car.*']))
    <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Car Records</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
				@if($user->hasAccess(['admin.car.carinspection']))
                 <li><a href="{!! route('admin.car.carinspection') !!}"><i class="fa fa-circle-o"></i>New Car Inspection</a></li>
                @endif
                @if($user->hasAccess(['admin.car.inspectedcar']))
                <li><a href="{!! route('admin.car.inspectedcar') !!}"><i class="fa fa-circle-o"></i>Inspected Car</a></li>
                @endif
                @if($user->hasAccess(['admin.car.fullcarrecord']))
                 <li><a href="{!! route('admin.car.fullcarrecord') !!}"><i class="fa fa-circle-o"></i>Full Car Record</a></li>
                @endif
                @if($user->hasAccess(['admin.car.allcarrecords']))
                <li><a href="{!! route('admin.car.allcarrecords') !!}"><i class="fa fa-circle-o"></i>All Car Records</a></li>
                @endif
                
                
                
              </ul>
     </li>
     @endif
      @if($user->hasAccess(['admin.environmental.*']))
      <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Environmental Records</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
			   @if($user->hasAccess(['admin.environmental.newenvironmentalrecord']))
                <li><a href="{!! route('admin.environmental.newenvironmentalrecord') !!}"><i class="fa fa-circle-o"></i>New Environmental Record</a></li>
               @endif
               @if($user->hasAccess(['admin.environmental.allenvironmentalrecords']))
               <li><a href="{!! route('admin.environmental.allenvironmentalrecords') !!}"><i class="fa fa-circle-o"></i>All Environmental Records</a></li>
                @endif
                
              </ul>
     </li>
     @endif
      @if($user->hasAccess(['admin.invoice.*']))
     <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Invoice Manager</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
			    @if($user->hasAccess(['admin.invoice.newinvoice']))
                 <li><a href="{!! route('admin.invoice.newinvoice') !!}"><i class="fa fa-circle-o"></i>New Invoice</a></li>
                @endif
                @if($user->hasAccess(['admin.invoice.allinvoice']))
                <li><a href="{!! route('admin.invoice.allinvoice') !!}"><i class="fa fa-circle-o"></i>All Invoice</a></li>
               @endif
                
                
               
              </ul>
     </li>
     @endif
      @if($user->hasAccess(['admin.users.*']))
     <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>User Manager</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                @if($user->hasAccess(['admin.users.register']))
               <li><a href="{!! route('admin.users.register') !!}"><i class="fa fa-circle-o"></i>New User</a></li>
                @endif
                @if($user->hasAccess(['admin.users.listuser']))
                <li><a href="{!! route('admin.users.listuser') !!}"><i class="fa fa-circle-o"></i>All System Users</a></li>
                @endif
                @if($user->hasAccess(['admin.users.usersroles']))
                <li><a href="{!! route('admin.users.usersroles') !!}"><i class="fa fa-circle-o"></i>User Roles</a></li>
                @endif
                
                
                
               
              </ul>
     </li>
     @endif
     @if($user->hasAccess(['admin.analysis.*']))
     <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Record Analysis</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
				@if($user->hasAccess(['admin.analysis.carrecords']))
                <li><a href="{!! route('admin.analysis.carrecords') !!}"><i class="fa fa-circle-o"></i>Car Records</a></li>
                @endif
                @if($user->hasAccess(['admin.analysis.envrecords']))
                 <li><a href="{!! route('admin.analysis.envrecords') !!}"><i class="fa fa-circle-o"></i>Environmental Records</a></li>
                @endif
                @if($user->hasAccess(['admin.analysis.quartiles']))
                 <li><a href="{!! route('admin.analysis.quartiles') !!}"><i class="fa fa-circle-o"></i>Quartiles</a></li>
                @endif
                
              </ul>
     </li>
      @endif
       @if($user->hasAccess(['admin.reprints']))
     <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Reprints Manager</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              
               <li><a href="{!! route('admin.reprints.all') !!}"><i class="fa fa-circle-o"></i>Car Record Reprints</a></li>
               
                
              </ul>
     </li>
     @endif
      @if($user->hasAccess(['admin.edits']))
     <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Edits Manager</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              
               <li><a href="{!! route('admin.edits.all') !!}"><i class="fa fa-circle-o"></i>Car Record Edits</a></li>
               
                
              </ul>
     </li>
     @endif
      
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>